### ISSUE TITLE
Testing app requires federation app to be enabled

### ISSUE THREAD

**Issue by phil-davis** [owncloud/testing#117]
It looks like PR #101 added features to the testing app that require the `federation` app to be enabled.

- check if this is true (disable `federation` and then try to run some ordinary acceptance tests that should run without federation)
- think of a way to adjust the testing app so that it can do its job, and still work cleanly (maybe with a little less functionality) when the `federation` app is disabled
- think if there are other core apps that the testing app depends on, and what we could do about that
- document whatever dependencies are unavoidable

**Comment by skshetry** [comment]
@phil-davis, currently, if the `federation` app cannot be started, there are no imported modules that we can use in the `testing` app. This would have been fine if the Http response to the APIs in the `testing` app would throw some 4XX/5XX status code (better response is always better, though). 

Sadly, the response is `200 OK` and empty *body* content, which will pass most of our assertions (where we check that status code is `200`) and gives very ambiguous parsing errors (eg. where we do `res.json()`).

When the testing app fails, it should give 5XX errors, not `200`. We should prioritize this at least in this sprint or the very next. 

cc @HariBhandari07

**Comment by phil-davis** [comment]
This was noticed when trying to run a selection of acceptance tests against a system that had `federation` disabled. In that situation we should still be able to run "ordinary" acceptance test scenarios that do not need or test the federation features.
