### ISSUE TITLE
Add getAppValue and getAppValues functionality

### ISSUE THREAD

**Issue by phil-davis** [owncloud/testing#28]
Currently we can ``setAppValue`` ``setAppValues`` ``deleteAppValue`` and ``deleteAppValues``.

Code that wants to ``getAppValue`` or ``getAppValues`` is currently doing a remote ``occ`` command to display and return each app value that it cares about. It will be much more efficient to provide a ``get`` method where we already have a ``post``  and a ``delete`` method.

**Comment by paurakhsharma** [comment]
Can this be closed now?
